# Generated by Django 6.0.7 on 2026-07-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('diverse', 'Diverse')], max_length=10)),
                ('diagnosis', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Outpatient', 'Outpatient'), ('Inpatient', 'Inpatient')], max_length=20)),
                ('last_visit', models.DateField()),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('doctor', models.CharField(max_length=150)),
                ('ward', models.CharField(max_length=150)),
                ('address_street', models.CharField(max_length=255)),
                ('address_zip', models.CharField(max_length=20)),
                ('address_city', models.CharField(max_length=150)),
                ('emergency_contact_name', models.CharField(max_length=150)),
                ('emergency_contact_relation', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=50)),
                ('insurance_provider', models.CharField(max_length=150)),
                ('insurance_policy_number', models.CharField(max_length=100)),
                ('vitals_blood_pressure', models.CharField(max_length=50)),
                ('vitals_heart_rate', models.CharField(max_length=50)),
                ('vitals_oxygen_saturation', models.CharField(max_length=50)),
                ('vitals_temperature', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dosage', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Visit', 'Visit'), ('Procedure', 'Procedure'), ('Finding', 'Finding'), ('Medication', 'Medication'), ('Follow-up', 'Follow-up')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('doctor', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='patients.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
            ],
        ),
    ]
