# Generated by Django 5.2.16 on 2026-07-16 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imaging', '0003_remove_study_xray_file_xrayimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('xray_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='imaging.xrayimage')),
            ],
        ),
    ]
