# Generated by Django 5.2.16 on 2026-07-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='xray_file',
            field=models.FileField(blank=True, null=True, upload_to='studies/'),
        ),
        migrations.DeleteModel(
            name='XRayImage',
        ),
    ]
