# Generated by Django 5.2.16 on 2026-07-16 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0002_study_xray_file_delete_xrayimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='xray_file',
        ),
        migrations.CreateModel(
            name='XRayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='xray_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prediction_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imaging.study')),
            ],
        ),
    ]
